var baseUrl = "/static/analytics/js/helpers/";

var c = cube("C", "Le cube")
  .measure("E", "Export", function (index) { return Math.abs(Math.sin(Math.PI/(index+1))); })
  .measure("I", "Import", function (index) { return Math.sqrt(index); })
  .dimension("[Zone]", "Zone", "Geometry")
    .hierarchy("Z1", "Nuts")
      .level("nuts0", "Nuts0")
        .property("Geom", "La Geometrie", "Geometry")
        .member("BE", "Belgium", {"Geom": fileContent(baseUrl+"geoData/BE")}, ["BE1","BE2","BE3"])
        .member("DE", "Germany", {"Geom": fileContent(baseUrl+"geoData/DE")}, ["DE7","DEC","DE9","DEB","DE3","DEG","DEF","DE8","DE4","DEA","DEE","DE1","DE2","DE6","DE5","DED"])
        .member("NL", "Netherlands", {"Geom": fileContent(baseUrl+"geoData/NL")}, ["NL4","NL3","NL1","NL2"])
        .member("LU", "Luxembourg", {"Geom": fileContent(baseUrl+"geoData/LU")}, ["LU0"])
        .member("UK", "United Kingdom", {"Geom": fileContent(baseUrl+"geoData/UK")}, ["UKI","UKC","UKM","UKG","UKD","UKF","UKH","UKL","UKN","UKJ","UKK","UKE"])
      .level("nuts1", "Nuts1")
        .property("Geom", "La Geometrie", "Geometry")
        .member("BE3", "RÉGION WALLONNE", {"Geom": fileContent(baseUrl+"geoData/BE3")}, [])
        .member("BE2", "VLAAMS GEWEST", {"Geom": fileContent(baseUrl+"geoData/BE2")}, [])
        .member("BE1", "RÉGION DE BRUXELLES-CAPITALE / BRUSSELS HOOFDSTEDELIJK GEWEST", {"Geom": fileContent(baseUrl+"geoData/BE1")}, [])
        .member("DE7", "HESSEN", {"Geom": fileContent(baseUrl+"geoData/DE7")}, [])
        .member("DEC", "SAARLAND", {"Geom": fileContent(baseUrl+"geoData/DEC")}, [])
        .member("DE9", "NIEDERSACHSEN", {"Geom": fileContent(baseUrl+"geoData/DE9")}, [])
        .member("DEB", "RHEINLAND-PFALZ", {"Geom": fileContent(baseUrl+"geoData/DEB")}, [])
        .member("DE3", "BERLIN", {"Geom": fileContent(baseUrl+"geoData/DE3")}, [])
        .member("DEG", "THÜRINGEN", {"Geom": fileContent(baseUrl+"geoData/DEG")}, [])
        .member("DEF", "SCHLESWIG-HOLSTEIN", {"Geom": fileContent(baseUrl+"geoData/DEF")}, [])
        .member("DE8", "MECKLENBURG-VORPOMMERN", {"Geom": fileContent(baseUrl+"geoData/DE8")}, [])
        .member("DE4", "BRANDENBURG", {"Geom": fileContent(baseUrl+"geoData/DE4")}, [])
        .member("DEA", "NORDRHEIN-WESTFALEN", {"Geom": fileContent(baseUrl+"geoData/DEA")}, [])
        .member("DEE", "SACHSEN-ANHALT", {"Geom": fileContent(baseUrl+"geoData/DEE")}, [])
        .member("DE1", "BADEN-WÜRTTEMBERG", {"Geom": fileContent(baseUrl+"geoData/DE1")}, [])
        .member("DE2", "BAYERN", {"Geom": fileContent(baseUrl+"geoData/DE2")}, [])
        .member("DE6", "HAMBURG", {"Geom": fileContent(baseUrl+"geoData/DE6")}, [])
        .member("DE5", "BREMEN", {"Geom": fileContent(baseUrl+"geoData/DE5")}, [])
        .member("DED", "SACHSEN", {"Geom": fileContent(baseUrl+"geoData/DED")}, [])
        .member("LU0", "LUXEMBOURG", {"Geom": fileContent(baseUrl+"geoData/LU0")}, [])
        .member("NL4", "ZUID-NEDERLAND", {"Geom": fileContent(baseUrl+"geoData/NL4")}, [])
        .member("NL3", "WEST-NEDERLAND", {"Geom": fileContent(baseUrl+"geoData/NL3")}, [])
        .member("NL1", "NOORD-NEDERLAND", {"Geom": fileContent(baseUrl+"geoData/NL1")}, [])
        .member("NL2", "OOST-NEDERLAND", {"Geom": fileContent(baseUrl+"geoData/NL2")}, [])
        .member("UKI", "LONDON", {"Geom": fileContent(baseUrl+"geoData/UKI")}, [])
        .member("UKC", "NORTH EAST (ENGLAND)", {"Geom": fileContent(baseUrl+"geoData/UKC")}, [])
        .member("UKM", "SCOTLAND", {"Geom": fileContent(baseUrl+"geoData/UKM")}, [])
        .member("UKG", "WEST MIDLANDS (ENGLAND)", {"Geom": fileContent(baseUrl+"geoData/UKG")}, [])
        .member("UKD", "NORTH WEST (ENGLAND)", {"Geom": fileContent(baseUrl+"geoData/UKD")}, [])
        .member("UKF", "EAST MIDLANDS (ENGLAND)", {"Geom": fileContent(baseUrl+"geoData/UKF")}, [])
        .member("UKH", "EAST OF ENGLAND", {"Geom": fileContent(baseUrl+"geoData/UKH")}, [])
        .member("UKL", "WALES", {"Geom": fileContent(baseUrl+"geoData/UKL")}, [])
        .member("UKN", "NORTHERN IRELAND", {"Geom": fileContent(baseUrl+"geoData/UKN")}, [])
        .member("UKJ", "SOUTH EAST (ENGLAND)", {"Geom": fileContent(baseUrl+"geoData/UKJ")}, [])
        .member("UKK", "SOUTH WEST (ENGLAND)", {"Geom": fileContent(baseUrl+"geoData/UKK")}, [])
        .member("UKE", "YORKSHIRE AND THE HUMBER", {"Geom": fileContent(baseUrl+"geoData/UKE")}, [])
  .dimension("[Time]", "Temps", "Time")
    .hierarchy("T1", "Years-Semesters")
      .level("Level0", "Years")
        .member("2010", "2010", {}, ["2010-S1", "2010-S2"])
        .member("2011", "2011", {}, ["2011-S1", "2011-S2"])
        .member("2012", "2012", {}, ["2012-S1", "2012-S2"])
        .member("2013", "2013", {}, ["2013-S1", "2013-S2"])
      .level("Level1", "Semester")
        .member("2010-S1", "2010-S1")
        .member("2010-S2", "2010-S2")
        .member("2011-S1", "2011-S1")
        .member("2011-S2", "2011-S2")
        .member("2012-S1", "2012-S1")
        .member("2012-S2", "2012-S2")
        .member("2013-S1", "2013-S1")
        .member("2013-S2", "2013-S2")
        .member("2014-S1", "2014-S1")
        .member("2014-S2", "2014-S2")
  .dimension("[Product]", "Product", "Standard")
    .hierarchy("P1", "Custom type")
      .level("Level0", "type")
        .member("F", "Food", {}, ["BG","P","S"])
        .member("NC", "Non-consumable", {}, ["H","F"])
      .level("Level1", "Semester")
        .member("BG", "Backing Goods")
        .member("P", "Produce")
        .member("S", "Snack Goods")
        .member("H", "Hammer")
        .member("F", "Fork");
